#!/bin/bash
# Mechanically write out user.conf.local.
#   ./write-user-conf.sh <username> [account] [partition] [identity_file]
# Overwrites any existing file. Normally invoked by Claude inside the setup flow.

set -u
source "$(dirname "$0")/common.sh"

username="${1:-}"
account="${2:-watanabemc}"
partition="${3:-amd}"
identity_file="${4:-}"

if [[ -z "$username" ]]; then
    err "Usage: write-user-conf.sh <username> [account] [partition] [identity_file]"
    exit 2
fi

cat > "$USER_CONF" <<EOF
# HPC4 personal config. Auto-generated by the setup flow. Hand-editable.
# This file is gitignored (not part of the repo).

HPC4_USER="${username}"
HPC4_ACCOUNT="${account}"
HPC4_PARTITION="${partition}"
HPC4_IDENTITY_FILE="${identity_file}"
EOF

ok "Wrote: $USER_CONF"
printf "  HPC4_USER=%s\n  HPC4_ACCOUNT=%s\n  HPC4_PARTITION=%s\n  HPC4_IDENTITY_FILE=%s\n" \
    "$username" "$account" "$partition" "$identity_file"
